/*
 * generated by Xtext
 */
package org.kermeta.language.sample.cellularautomata.rules;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CoreRuntimeModule extends org.kermeta.language.sample.cellularautomata.rules.AbstractCoreRuntimeModule {

}
