@startuml

skinparam class {
	BackgroundColor White
	ArrowColor Black
	BorderColor Black
}

package multiparent {
class Parent1 {
}

class Parent2 {
}

class Parent3{
}

class Child{
}

Parent1 <|- Child
Parent2 <|- Child
Parent3 <|- Child

}

@enduml
