/*
* generated by Xtext
*/
package insa;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LegoStandaloneSetup extends LegoStandaloneSetupGenerated{

	public static void doSetup() {
		new LegoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

