/*
 * generated by Xtext
 */
package insa;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LegoRuntimeModule extends insa.AbstractLegoRuntimeModule {

}
