<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fr" nsURI="http://www.fr.inria.triskell.kompren/fr" nsPrefix="fr">
  <eSubpackages name="inria" nsURI="http://www.fr.inria.triskell.kompren/fr/inria"
      nsPrefix="fr.inria">
    <eSubpackages name="triskell" nsURI="http://www.fr.inria.triskell.kompren/fr/inria/triskell"
        nsPrefix="fr.inria.triskell">
      <eSubpackages name="kompren" nsURI="http://www.fr.inria.triskell.kompren/fr/inria/triskell/kompren"
          nsPrefix="fr.inria.triskell.kompren">
        <eSubpackages name="slicer" nsURI="http://www.fr.inria.triskell.kompren/fr/inria/triskell/kompren/slicer"
            nsPrefix="fr.inria.triskell.kompren.slicer">
          <eClassifiers xsi:type="ecore:EClass" name="Slicer">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriMetamodel" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="strict" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="helper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="onStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="onEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
                eType="#//inria/triskell/kompren/slicer/Constraint" containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="radius" eType="#//inria/triskell/kompren/slicer/Radius"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="slicedElements"
                upperBound="-1" eType="#//inria/triskell/kompren/slicer/SlicedElement"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="inputClasses" lowerBound="1"
                upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Constraint">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="Radius">
            <eStructuralFeatures xsi:type="ecore:EReference" name="focusedClasses"
                upperBound="-1" eType="#//inria/triskell/kompren/slicer/SlicedClass"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SlicedClass" eSuperTypes="#//inria/triskell/kompren/slicer/SlicedElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="ctx" eType="#//inria/triskell/kompren/slicer/VarDecl"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
                eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SlicedProperty" eSuperTypes="#//inria/triskell/kompren/slicer/SlicedElement">
            <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//inria/triskell/kompren/slicer/OppositeCreation"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="#//inria/triskell/kompren/slicer/VarDecl"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="tgt" eType="#//inria/triskell/kompren/slicer/VarDecl"
                containment="true"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
                eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="OppositeCreation">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="SlicedElement" abstract="true">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eClassifiers>
          <eClassifiers xsi:type="ecore:EClass" name="VarDecl">
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="varName" lowerBound="1"
                eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
                eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
          </eClassifiers>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
