/*
 * generated by Xtext
 */
package insa.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLegoValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://TPIDMINSA/robot"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://TPIDMINSA/MRL"));
		return result;
	}
}
