/*
 * generated by Xtext
 */
package insa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import insa.ui.internal.ExpArithmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExpArithmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExpArithmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExpArithmActivator.getInstance().getInjector(ExpArithmActivator.INSA_EXPARITHM);
	}
	
}
