/*
 * generated by Xtext
 */
package org.kermeta.language.sample.cellularautomata.rules.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CoreUiModule extends org.kermeta.language.sample.cellularautomata.rules.ui.AbstractCoreUiModule {
	public CoreUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
