<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statemachine" nsURI="http:///statemachine.ecore" nsPrefix="statemachine">
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eOperations name="addState" eType="#//State">
      <eParameters name="initial" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="terminal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="terminals">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
    </eOperations>
    <eOperations name="accessibleStates">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
    </eOperations>
    <eOperations name="accessibleStates">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
      <eParameters name="states">
        <eGenericType eClassifier="#//Set">
          <eTypeArguments eClassifier="#//State"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="coAccessibleStates">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
      <eParameters name="states">
        <eGenericType eClassifier="#//Set">
          <eTypeArguments eClassifier="#//State"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="coAccessibleStates">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
    </eOperations>
    <eOperations name="accessibleAndCoAccessibleStates">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
    </eOperations>
    <eOperations name="deltaFrom">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//Transition"/>
      </eGenericType>
      <eParameters name="from" eType="#//State"/>
      <eParameters name="to" eType="#//State"/>
    </eOperations>
    <eOperations name="deltaMinusOne">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//Transition"/>
      </eGenericType>
      <eParameters name="state" eType="#//State"/>
      <eParameters name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="addTransition">
      <eParameters name="transition" eType="#//Transition"/>
    </eOperations>
    <eOperations name="accessibleStates">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
      <eParameters name="st" eType="#//State"/>
    </eOperations>
    <eOperations name="accept" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="word" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="alphabet">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eOperations>
    <eOperations name="delta">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//Transition"/>
      </eGenericType>
      <eParameters name="state" eType="#//State"/>
      <eParameters name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="delta">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//Transition"/>
      </eGenericType>
      <eParameters name="state" eType="#//State"/>
    </eOperations>
    <eOperations name="delta">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//Transition"/>
      </eGenericType>
      <eParameters name="s">
        <eGenericType eClassifier="#//Set">
          <eTypeArguments eClassifier="#//State"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="steps">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
      <eParameters name="s">
        <eGenericType eClassifier="#//Set">
          <eTypeArguments eClassifier="#//State"/>
        </eGenericType>
      </eParameters>
      <eParameters name="word" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="steps">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
      <eParameters name="st" eType="#//State"/>
      <eParameters name="word" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="step">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
      <eParameters name="s">
        <eGenericType eClassifier="#//Set">
          <eTypeArguments eClassifier="#//State"/>
        </eGenericType>
      </eParameters>
      <eParameters name="o" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="initials">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//State"/>
      </eGenericType>
    </eOperations>
    <eOperations name="deltaMinusOne">
      <eGenericType eClassifier="#//Set">
        <eTypeArguments eClassifier="#//Transition"/>
      </eGenericType>
      <eParameters name="st" eType="#//State"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delta" upperBound="-1"
        eType="#//Transition" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Set" instanceClassName="java.util.Set"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
  </eClassifiers>
</ecore:EPackage>
