/*
 * generated by Xtext
 */
package insa.ui.contentassist

import insa.ui.contentassist.AbstractExpArithmProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ExpArithmProposalProvider extends AbstractExpArithmProposalProvider {
}
