<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vm" nsURI="http://vm/1.0" nsPrefix="vm">
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbors" upperBound="-1"
        eType="#//Cell"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Universe">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
