/*
* generated by Xtext
*/
package org.kermeta.language.sample.cellularautomata.rules.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.kermeta.language.sample.cellularautomata.rules.services.EvolGrammarAccess;

public class EvolParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EvolGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.kermeta.language.sample.cellularautomata.rules.parser.antlr.internal.InternalEvolParser createParser(XtextTokenStream stream) {
		return new org.kermeta.language.sample.cellularautomata.rules.parser.antlr.internal.InternalEvolParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CellularAutomata";
	}
	
	public EvolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EvolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
