@startuml

skinparam class {
	BackgroundColor White
	ArrowColor Black
	BorderColor Black
}
package designbycontract {
	class	TestDbC {
		 testOkInv()
		 testNOKInv()
		 testOKPrePost()
		 testOKAll()
		 testNOKPreCond()
		 testNOKPostCondition()
		 testOKInvNOKPre()
		 testOKInvNOKPost()
		 testNOKInvOKPre()
		 testNOKInvOKPost()
		 testInvBrokenByFoo()
	}
	class	SimpleOKInv {
		boolean inv()
		void foo()
	}
	class	SimpleNOKInv {
		boolean inv()
		void foo()
	}
	class	SimpleOKPrePost {
		boolean preFoo()
		boolean postFoo()
		void foo()
	}
	class	SimpleOKAll {
		boolean inv()
		boolean preFoo()
		boolean postFoo()
		void foo()
	}
	class	SimpleNOKPreCond {
		boolean preFoo()
		void foo()
	}
	class	SimpleNOKPostCond {
		boolean postFoo()
		void foo()
	}
	class	SimpleOKInvNOKPre {
		boolean inv()
		boolean preFoo()
		void foo()
	}
	class	SimpleOKInvNOKPost {
		boolean inv()
		boolean postFoo()
		void foo()
	}
	class	SimpleNOKInvOKPre {
		boolean inv()
		boolean preFoo()
		void foo()
	}
	class	SimpleNOKInvOKPost {
		boolean inv()
		boolean postFoo()
		void foo()
	}
	class	SimpleInvBrokenByFoo {
		i : int
		boolean inv()
		void foo()
	}
	class	TestCase {
		 testPre()
		void testInv()
		void testPost()
		void testPreInheritance()
		void testPreInheritance1()
		void testInvInheritance()
		void testPostInheritance()
		void testPostInheritance1()
	}
	class	RewriteMe {
		void foo()
		boolean preFoo()
	}
	class	RewriteMe1 {
		boolean inv1()
		void foo()
	}
	class	RewriteMe2 {
		void foo()
		boolean postFoo()
	}
	abstract	ADbc {
		name : String
		boolean preFoo()
		void foo()
		boolean preBar()
		void bar()
	}
	class	BDbc {
		name : String
		void foo()
		boolean preFoo()
		boolean preBar()
		void bar()
	}
	abstract	ADbc1 {
		name : String
		boolean inv1()
		void foo()
	}
	class	BDbc1 {
		name : String
		boolean inv2()
		void foo()
	}
	abstract	ADbc2 {
		name : String
		void bar()
		boolean postBar()
		void foo()
		boolean postFoo()
	}
	class	BDbc2 {
		name : String
		void bar()
		boolean postBar()
		void foo()
		boolean postFoo()
	}
}
ADbc <|-- BDbc      
ADbc1 <|-- BDbc1      
ADbc2 <|-- BDbc2      
@enduml
