<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RDBMSMM" nsURI="platform:/resource/fr.irisa.triskell.kermeta.samples/class2RDBMS/metamodels/RDBMSMM.ecore"
    nsPrefix="RDBMSMM">
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cols" lowerBound="1" upperBound="-1"
        eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pkey" lowerBound="1" upperBound="-1"
        eType="#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fkeys" upperBound="-1"
        eType="#//FKey" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" lowerBound="1"
        eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cols" lowerBound="1" upperBound="-1"
        eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RDBMSModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" upperBound="-1"
        eType="#//Table" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
</ecore:EPackage>
