/*
 * generated by Xtext
 */
package insa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExpArithmUiModule extends insa.ui.AbstractExpArithmUiModule {
	public ExpArithmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
		return ExpHighlightingConfiguration.class;
	}
	 
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		return ExpHighlightingCalculator.class;
	}
}
