== Language Reference

=== Basic

==== Creating an aspect on a class
1. Add the annotation _**Aspect**_ on the class corresponding to the aspect
2. Specify the class to augment using the annotation parameter **className**
3. Update the imported packages using **ctrl+shift+o**


```k3
package mypackage

import fr.inria.triskell.k3.Aspect

import mypackage.OtherClass

@Aspect(className=OtherClass)
class OtherClassAspect {
    def void display (){
         prinln("I am OtherClassAspect")
    }
}
```

In an aspect you can use the attributes and operations of both the augmented class and the aspect itself.<br/>
In aspects **the keyword** "_**this**_" **must not be used**.
Instead, the keyword "**_self**" must be used.

```k3
@Aspect(className=OtherClass)
class OtherClassAspect {
   var int foo = 1

    def void display (){
         // The keyword _self must be used to refer to attributes and operations of the class and aspect.
         _self.foo = 2
         _self.callingOnOperationOfOtherClass()
    }
}
```

Despite it should be legal, due to a bug in xtend, we **do not** recommand the following syntax:
```
@Aspect(className=typeof(OtherClass))
```
It may raise strange scope issue, especially in case of aspects defined in several packages.

==== Extending an aspect

Extending an aspect can be performed as in Xtend.<br/>
However, an aspect can inherit from another aspect only!<br/>
To use the operations and attributes added in a class, you have to import the aspect:
_import static extension myPkg.AspectName.*_

```k3
package mypackage

import fr.inria.triskell.k3.Aspect
import fr.inria.triskell.k3.OverrideAspectMethod

import mypackage.OtherClass
import mypackage.MyClass

import static extension mypackage.OtherClassAspect.*

@Aspect(className=OtherClass)
class OtherClassAspect {
    def void display(){
      prinln("I am OtherClassAspect")
    }
}

@Aspect(className=MyClass)
class MyClassAspect extends OtherClassAspect {
    // Annotation to tag the operation as an operation 
    // overloading a super operation
    @OverrideAspectMethod
    def void display(){
      println("I am MyClassAspect")
    }
}
```

==== Calling a super operation
A call to a super operation can be done by writing **super_** followed by the name of the operation. Do not forget to use **_self** to handle elements of the class or aspect.

```k3
@Aspect(className=MyClass)
class MyClassAspect extends OtherClassAspect {
    @OverrideAspectMethod
    def void display(){
       _self.super_display()
       prinln("I am MyClassAspect")
    }
}
```


=== Advanced