/*
* generated by Xtext
*/
package org.kermeta.language.sample.cellularautomata.rules.ui.contentassist;

import org.kermeta.language.sample.cellularautomata.rules.ui.contentassist.AbstractCoreProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CoreProposalProvider extends AbstractCoreProposalProvider {

}
