/*
* generated by Xtext
*/
package fr.inria.diverse.k3.sle.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class K3SLEAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/inria/diverse/k3/sle/parser/antlr/internal/InternalK3SLE.tokens");
	}
}
