/*
 * generated by Xtext
 */
package insa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LegoUiModule extends insa.ui.AbstractLegoUiModule {
	public LegoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
