/*
* generated by Xtext
*/
package insa;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ExpArithmStandaloneSetup extends ExpArithmStandaloneSetupGenerated{

	public static void doSetup() {
		new ExpArithmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

