/*
* generated by Xtext
*/
package org.kermeta.language.sample.cellularautomata.rules.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CoreOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
