@startuml

participant XtendCompiler as XtendCompiler
participant AspectProcessor as Processor
participant ProjectStaticDispatchBuilder
participant AspectMappingBuilder
participant RegisterGlobalsContext

note over of Processor
	Applies to classes with @Aspect annotation
end note

activate Processor

XtendCompiler -> Processor: doRegisterGlobals
Processor -> RegisterGlobalsContext: registerClass
XtendCompiler <-- Processor

XtendCompiler -> Processor: doTransform
Processor -> Processor: initSuperclass
Processor -> Processor: initDispatchmethod
group for classes with Aspect annotation
	Processor -> Processor: fieldsProcessing
	activate Processor
		Processor -> Processor: fieldProcessingMoveField
		Processor -> Processor: fieldProcessingAddGetterSetter
		Processor --> Processor
		note right
			remove processed fields
		end note
	deactivate Processor
	Processor -> Processor: methodsProcessing
	activate Processor
		group for declaredMethods in class
			Processor -> Processor: checkAnnotationprocessorCorrect
			Processor -> Processor: methodProcessingAddSelfStatic
			Processor -> Processor: methodProcessingAddSuper
			Processor -> Processor: methodProcessingAddHidden
			Processor -> Processor: methodProcessingAddPriv
			Processor -> Processor: methodProcessingChangeBody
			activate Processor
				Processor -> Processor: surroundWithStepCommandExecution
				Processor -> ProjectStaticDispatchBuilder : findExistingDispatchCalls					
				Processor -> Processor: getBody
				Processor --> Processor
			deactivate Processor
		end
		Processor -> Processor: methodProcessingAddMultiInheritMeth
		Processor --> Processor
	deactivate Processor
	Processor -> Processor: constructorsProcessing
	Processor -> Processor: aspectContextMaker
end

note over AspectMappingBuilder
	The AspectMappingBuilder instance 
	is shared between jobs working 
	on the same eclipse project
end note
Processor -> AspectMappingBuilder: getAspectMappingBuilder
activate AspectMappingBuilder
Processor -> AspectMappingBuilder: readCurrentMapping
Processor -> AspectMappingBuilder: addMappingForAnnotatedSourceElements
XtendCompiler <-- Processor

XtendCompiler -> Processor: doValidate
Processor -> AspectMappingBuilder: cleanUnusedMapping
XtendCompiler <-- Processor

XtendCompiler -> Processor: doGenerateCode
Processor -> AspectMappingBuilder: writePropertyFile
deactivate AspectMappingBuilder
Processor -> Processor: generateAspectJCodeForClass
Processor -> Processor: injectDispatchInParentAspects
activate Processor
Processor -> ProjectStaticDispatchBuilder : add
Processor -> ProjectStaticDispatchBuilder : cleanDeprecatedDispatchFiles
Processor --> Processor
deactivate Processor
Processor -> ProjectStaticDispatchBuilder : writeTempStaticDispatchFile
XtendCompiler <-- Processor

deactivate Processor
@enduml