@startuml

participant XtendCompiler as XtendCompiler
participant CompositionProcessor as Processor
participant RegisterGlobalsContext

activate Processor

note over of Processor
	Applies to fields with @Composition annotation
end note
XtendCompiler -> Processor: doRegisterGlobals
Processor -> RegisterGlobalsContext: registerInterface
XtendCompiler <-- Processor

XtendCompiler -> Processor: doTransform
		Processor -> Processor: getObservabilityInterfaceName
		Processor -> Processor: getObservabilityOperationName
		Processor -> Processor
		note right
			do some work
			add getter and setter
		end note
XtendCompiler <-- Processor

XtendCompiler --> XtendCompiler: doValidate

XtendCompiler --> XtendCompiler: doGenerateCode

deactivate Processor
@enduml