/*
 * generated by Xtext
 */
package org.kermeta.language.sample.cellularautomata.rules.scoping;

import org.kermeta.language.sample.cellularautomata.rules.scoping.CoreScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class EvolScopeProvider extends CoreScopeProvider {

}
